version: '3.8'

services:
  tropico-poc:
    build: .
    container_name: tropico-poc-container
    ports:
      - "2222:22"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    env_file:
      - .env
    command: ["python", "main.py", "--mode", "llm"]
    restart: unless-stopped
