services:
  tropico-ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: tropico-ssh
    ports:
      - "2222:22"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - DEFAULT_USER=${DEFAULT_USER}
      - DEFAULT_HOSTNAME=${DEFAULT_HOSTNAME}
      - USER_PASSWORD=${USER_PASSWORD}
      - LOG_FILE=/logs/tropico-ssh.log
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    command: ["python", "ssh.py", "--mode", "llm"]
    restart: unless-stopped
  tropico-https:
    build:
      context: .
      dockerfile: Dockerfile.https  # Your HTTPS Dockerfile
    container_name: tropico-https
    ports:
      - "8443:443"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - LOG_FILE=/logs/tropico-https.log
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_CERT_KEY=${TLS_CERT_KEY}
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    restart: unless-stopped